version: 0.0
os: linux

files:
  - source: /
    destination: /usr/share/nginx/html/sample
    file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/restart_nginx.sh
      timeout: 60
      runas: root
